{% set name = "rotaconfort" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2781284664db6469ee417099bf44b6cf201cde695e0c7a9f8d8a657a93357c85
  git_url: https://github.com/jvalegre/RotaConfort
  git_tag: v_1.0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}

requirements:
  host:
    - python
  run:
    - python

test:
  imports:
    - DBGEN

about:
  home: https://github.com/jvalegre/RotaConfort
  license: MIT
  license_family: MIT
  license_file:
  summary: Conformer generation and post-processing of DFT output files
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - your-github-id-here
